version: "3.2"

services:
  gateway:
    # Image is maintained under: https://github.com/thin-edge/opcua-device-gateway-container
    image: ghcr.io/thin-edge/opcua-device-gateway:20240216.1552
    restart: always
    environment:
      # thin-edge.io MQTT broker
      - MQTT_BROKER=host.docker.internal:1883
      - DEVICE_ID=${DEVICE_ID:-}
      - C8Y_BASEURL=${C8Y_BASEURL:-}
    volumes:
      - opcua_data:/data
      # Provide access to thin-edge.io configuration
      - /etc/tedge:/etc/tedge
      - /etc/tedge/device-certs:/etc/tedge/device-certs
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - backend

volumes:
  opcua_data:

networks:
  backend:
